plugins {
    id 'org.springframework.boot'
    id 'org.springdoc.openapi-gradle-plugin' version "${openapiVersion}"
}

dependencies {
	implementation project(':reactive-web')
	implementation project(':logger-adapter')
	implementation project(':security')
	implementation project(':sqs-listener')
	implementation 'org.reactivecommons.utils:object-mapper:0.1.0'
	implementation project(':dynamo-db')
	implementation project(':metrics')
	implementation 'software.amazon.awssdk:sts'
    implementation project(':model')
    implementation project(':usecase')
    implementation 'org.springframework.boot:spring-boot-starter'
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
}

springBoot {
    mainClass = 'co.com.bancolombia.MainApplication'
}

tasks.named('bootRun') {
    mainClass = 'co.com.bancolombia.MainApplication'
}

openApi {
    apiDocsUrl = 'http://localhost:8085/v3/api-docs'
    outputDir = file("$buildDir/openapi")
    outputFileName = 'openapi.json'
    waitTimeInSeconds = 25
    customBootRun {
        systemProperties = [
                'server.port': '8085',
                'spring.profiles.active': 'openapi'
        ]
        jvmArgs = ['-Dspring.main.lazy-initialization=true']
    }
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    // Sets output jar name
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}